name: Update README Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=sergiuNE&show_icons=true&include_all_commits=true&hide=contribs&custom_title=Sergiu's%20GitHub%20Stats&title_color=4FC3F7&icon_color=4FC3F7&text_color=2E3A59&bg_color=FFFFFF&border_color=E0E0E0
          path: stats.svg

      - name: Generate top languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=sergiuNE&show_icons=true&include_all_commits=true&hide=issues,contribs&show=prs_merged,prs_merged_percentage&custom_title=Sergiu%20Neagu%20-%20GitHub%20Overview&title_color=4FC3F7&icon_color=4FC3F7&text_color=2E3A59&bg_color=FFFFFF&border_color=E0E0E0
          path: top-langs.svg

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add *.svg
          git commit -m "Update stats" || exit 0
          git push
